### ISSUE TITLE
ngu-pw-manifest not recognized

### ISSUE THREAD

**Issue by markgoho** [alxhub/io17#5]
```
PS C:\Users\Nella\Documents\GitHub\io17> ngu-pw-manifest
ngu-pw-manifest : The term 'ngu-pw-manifest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
```

Is this supposed to be run in any kind of special way?

**Comment by mithilgotarne** [comment]
make sure you have installed ng-pwa-tools
`npm install ng-pwa-tools`

if you are using windows, use bash shell or git bash to run command 
`./node_modules/.bin/ngu-sw-manifest`
P.S.: this command wont run on windows cmd

**Comment by markgoho** [comment]
Thanks a MILLION @mithilgotarne!!!

This worked perfectly using git bash. I have no idea _how_ this works, but I'm thankful you supplied the answer! I'm guessing the other commands that @alxhub runs should be done in a similar fashion.

**Comment by alxhub** [comment]
@markgoho, I've not tested on Windows. Also, I do:
```bash
$ export PATH="$PATH:$(npm bin)"
```
which allows me to run executable scripts in the project `node_modules/.bin` directory without prefixing them.

**Comment by markgoho** [comment]
Apparently, Windows doesn't like `$(npm bin)` either -- I'll stick with the ./node_modules etc. way of doing it. Hopefully in future releases of the tools, we can figure out a platform-agnostic way of running the scripts.... but that's way beyond me :)

**Comment by MatteoNY** [comment]
Thanks for the tip (Mac)  export PATH="$PATH:$(npm bin)" fixed issue for running ngu-sw-manifest command from terminal. :-)
