### ISSUE TITLE
Failing on windows

### ISSUE THREAD

**Issue by BorntraegerMarc** [alxhub/io17#9]
I get this error on Windows:
```
D:\projects\komed-health-web>ngu-sw-manifest
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by BorntraegerMarc** [comment]
Solved it by adding a npm script `"ngu-sw-manifest": "node ./node_modules/ng-pwa-tools/bin/ngu-sw-manifest.js"`

**Comment by BorntraegerMarc** [comment]
Also with the suggested way of running it from windows I get:
```
D:\projects\komed-health-web>./node_modules/.bin/ngu-sw-manifest
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by markgoho** [comment]
Hey @BorntraegerMarc are you running these commands inside Bash? They will not work from Windows Command prompt or Powershell

**Comment by BorntraegerMarc** [comment]
@markgoho Thanks for the reply. I have the same issues with git bash...

**Comment by jamajamik** [comment]
Replacing all "/" with "\\" in node_modules\\.bin\\ngu_XX_command.cmd seems to resolve that for bash.
